#-------------------------------
# General Site Settings

title: Exaberry
logo:
author:
description:
email:
phone:
address:
copyright: Copyright &copy; 2021 Exaberry

menu:
- {name: Specifications, link: '/specifications'}
- {name: About, link: '/about'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hardware as a command line tool
  hero-subtitle: Plug & play sensors and drivers accelerating your innovation and empowering your development

# social:
# - {icon: "ti-facebook", link: "#"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# Features Section

features-title: Features
features:
- {
    name: Command driven,
    image: "assets/images/features/command_driven.png",
    description: 'The device has a command line parser built in. To operate the device, you can send commands to the device through a terminal.',
    active: # Add true to select section
  }
- {
    name: USB connected,
    image: "assets/images/features/usb_connected.png",
    description: 'USB port is widely available. It is super easy to connect your device to a laptop, a single board computer, a tablet or a phone.',
    active: # Add true to select section
  }
- {
    name: UART connected,
    image: "assets/images/features/uart.png",
    description: 'Besides USB connection, UART connection is also an option. The UART pins are on the bottom side of the device.',
    active: # Add true to select section
  }
- {
    name: Status LED,
    image: "assets/images/features/status_led.png",
    description: 'The red LED light blinks every two second to show the healthiness of the device.',
    active: # Add true to select section
  }
- {
    name: Tiny,
    image: "assets/images/features/tiny.png",
    description: 'Besides running the device in standalone mode. You can easily solder the device with your project without compromise the portability and size.',
    active: # Add true to select section
  }
- {
    name: Powerful,
    image: "assets/images/features/powerful.png",
    description: 'With a 72MHz processor, the command parsing is smooth and the sensor data processing is fast.',
    active: # Add true to select section
  }
- {
    name: Calibration available,
    image: "assets/images/features/calibration.png",
    description: 'Fine tune the accuracy of your device is not a problem. You can adjust the calibration parameters using commands. (device dependent)',
    active: # Add true to select section
  }
- {
    name: Documented,
    image: "assets/images/features/documented.png",
    description: 'Each device has a link to its documentation. Again, you can get the documentation link by command.',
    active: # Add true to select section
  }

#-------------------------------
# Devices Section

devices:
- name: Light sensor
  image: "assets/images/devices/light_front.png"
  description: 'Infrared, red, green, blue and ultraviolet light sensor combo with white led flash.'
  api_doc_url: "https://github.com/exaberry-devices/devices/blob/master/D034D0/README.md"
  available: false
- name: Weather sensor
  image: "assets/images/devices/weather_front.png"
  description: 'Measuring temperature, humidity and atmospheric pressure'
  api_doc_url: "https://github.com/exaberry-devices/devices/blob/master/D034D0/README.md"
  available: true
- name: ToF proximity sensor
  image: "assets/images/devices/distance_front.png"
  description: 'Laser time-of-flight proximity sensor with milimeter accuracy.'
  api_doc_url: "https://www.exaberry.org/"
  available: false

#- name: Weather sensors
#  image: "assets/images/features/tiny.png"
#  description: 'Measuring temperature, humidity and atmospheric pressure'
#  api_doc_url: "https://www.engadget.com/"
#  available: false

#-------------------------------
# getting started section
tutorial:
  image: "assets/images/tutorial/connection.png"

#-------------------------------
# About (Section and Page)

# story-section
stories:
  - title: "Engineer holding a device"
    image: "assets/images/about/eng.JPG"
  - title: "Device under test"
    image: "assets/images/about/test.JPG"
  - title: "Devices"
    image: "assets/images/about/prototypes.JPG"


#-------------------------------
# specifications

device-specification:
- image: "assets/images/specifications/top-view.png"
  items:
    - "Width: 10.8 mm"
    - "Length: > 16mm (device dependent)"
    - "Half hole diameter: 2.1 mm"
    - "Half holes center distance: 10.8 mm"
- image: "assets/images/specifications/side-view.png"
  items:
    - "PCB thickness: 1mm"
    - "USB port: Micro-USB"

