#-------------------------------
# General Site Settings

title: Exaberry
logo:
author:
description:
email:
phone:
address:
copyright: Copyright &copy; 2022 Exaberry

menu:
- {name: Getting Started, link: '/getting_started'}
- {name: Documentation, link: '/interface_documentation'}
# - {name: Store, link: '/store'}
- {name: Discord, external_link: 'https://discord.gg/5PZ557npFc'}
# - {name: About, link: '/about'}

footer_links:
- {name: Terms, link: '/terms'}


#-------------------------------
# Google Analytics Section

google-analytics: G-JNDK42TQYY


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Hardware as a command line tool
  hero-subtitle: Plug & play sensors and drivers accelerating your innovation and empowering your development

# social:
# - {icon: "ti-facebook", link: "#"}
# - {icon: "ti-instagram", link: "#"}
# - {icon: "ti-dribbble", link: "#"}
# - {icon: "ti-twitter", link: "#"}


#-------------------------------
# Features Section

features-title: Features
features:
- {
    name: Command driven,
    image: "assets/images/features/command_driven.png",
    description: 'The device has a command line parser built in. To operate the device, you can send commands to the device through a terminal.',
    active: # Add true to select section
  }
- {
    name: USB connected,
    image: "assets/images/features/usb_connected.png",
    description: 'USB port is widely available. It is super easy to connect your device to a laptop, a single board computer, a tablet or a phone.',
    active: # Add true to select section
  }
- {
    name: UART connected,
    image: "assets/images/features/uart.png",
    description: 'Besides USB connection, UART connection is also an option. The UART pins are on the bottom side of the device.',
    active: # Add true to select section
  }
- {
    name: Status LED,
    image: "assets/images/features/status_led.png",
    description: 'The red LED light blinks every two seconds to show the healthiness of the device.',
    active: # Add true to select section
  }
- {
    name: Tiny,
    image: "assets/images/features/tiny.png",
    description: 'Besides running the device in standalone mode. You can easily solder the device with your project without compromise the portability and size.',
    active: # Add true to select section
  }
- {
    name: Powerful,
    image: "assets/images/features/powerful.png",
    description: 'With a 72MHz processor, the command parsing is smooth and the sensor data processing is fast.',
    active: # Add true to select section
  }
- {
    name: Calibration available,
    image: "assets/images/features/calibration.png",
    description: 'Fine tune the accuracy of your device is not a problem. You can adjust the calibration parameters using commands. (device dependent)',
    active: # Add true to select section
  }
- {
    name: Documented,
    image: "assets/images/features/documented.png",
    description: 'Each device has a link to its documentation. Again, you can get the documentation link by command.',
    active: # Add true to select section
  }

#-------------------------------
# Devices Section

devices:
- name: Power relay
  image: "assets/images/devices/power_relay.png"
  description: '50 programmable on/off steps with milliseconds delay resolution'
  api_doc_url: "/devices/documentation/694705a14dad/1.0/api/"
  buy_link:
- name: Infrared thermometer
  image: "assets/images/devices/infrared_thermo_front.png"
  description: 'Infrared thermometer for non-contact temperature measurements.'
  api_doc_url: "/devices/documentation/edd61afb4ab1/1.0/api/"
  buy_link:
- name: Micro-controller
  image: "assets/images/devices/gpio.png"
  description: 'Micro-controller board with GPIO, DAC, ADC and PWM'
  api_doc_url: "/devices/documentation/0ea9052a3539/1.0/api/"
  buy_link:
- name: Weather sensors
  image: "assets/images/devices/weather_front.png"
  description: 'Measuring temperature, humidity and atmospheric pressure'
  api_doc_url: "/devices/documentation/7de673263d14/1.0/api/"
  buy_link:
- name: Light sensor
  image: "assets/images/devices/light_front.png"
  description: 'Infrared, red, green, blue and ultraviolet light sensor combo with white led flash.'
  api_doc_url:
  # api_doc_url: "https://github.com/exaberry-devices/devices/blob/master/D90234/v1.0/README.md"
  buy_link:
- name: ToF proximity sensor
  image: "assets/images/devices/distance_front.png"
  description: 'Laser time-of-flight proximity sensor with millimeter accuracy.'
  api_doc_url:
  # api_doc_url: "https://github.com/exaberry-devices/devices/blob/master/D87A80/v1.0/README.md"
  buy_link:

#-------------------------------
# getting started section
tutorial:
  image: "assets/images/tutorial/connection.png"

#-------------------------------
# About (Section and Page)

# story-section
# stories:
#   - title: "Engineer holding a device"
#     image: "assets/images/about/eng.JPG"
#   - title: "Device under test"
#     image: "assets/images/about/test.JPG"
#   - title: "Devices"
#     image: "assets/images/about/prototypes.JPG"


#-------------------------------
# specifications

# device-specification:
# - image: "assets/images/specifications/top-view.png"
#   items:
#     - "Half hole diameter: 2 mm"
#     - "Half holes center distance: 12 mm"
# - image: "assets/images/specifications/side-view.png"
#   items:
#     - "PCB thickness: 1mm"
#     - "USB port: Micro-USB"
#
